export const STARTER_TAPES = [
  {
    "id": "VHS-0001",
    "title": "Independence Day",
    "vhsYear": 1996,
    "studio": "Fox Video",
    "edition": "Standard",
    "packaging": "Cardboard Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0002",
    "title": "Grind",
    "vhsYear": 2003,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Cardboard Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0003",
    "title": "Twister",
    "vhsYear": 1996,
    "studio": "Widescreen Edition",
    "edition": "Widescreen",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "Warner Bros",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0004",
    "title": "E.T. the Extra-Terrestrial",
    "vhsYear": 1982,
    "studio": "MCA Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0005",
    "title": "Back to the Future Part III",
    "vhsYear": 1990,
    "studio": "MCA Universal Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0006",
    "title": "Back to the Future Part II",
    "vhsYear": 1989,
    "studio": "MCA Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0007",
    "title": "Back to the Future",
    "vhsYear": 1994,
    "studio": "MCA Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0008",
    "title": "The Incredibles",
    "vhsYear": 2005,
    "studio": "Disney Pixar",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0009",
    "title": "Demolition Man",
    "vhsYear": 1998,
    "studio": "Warner Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0010",
    "title": "Groundhog Day",
    "vhsYear": 1993,
    "studio": "Columbia Tristar Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0011",
    "title": "Mighty Ducks",
    "vhsYear": 1993,
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0012",
    "title": "Twins",
    "vhsYear": 1988,
    "studio": "MCA Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0013",
    "title": "Wayne's World 2",
    "vhsYear": 1993,
    "studio": "Paramount Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0014",
    "title": "South Park Bigger Longer Uncut",
    "vhsYear": 1999,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0015",
    "title": "The Mummy",
    "vhsYear": 1999,
    "studio": "Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0016",
    "title": "The Wizard",
    "vhsYear": 1989,
    "studio": "MCA Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0017",
    "title": "SpongeBob SquarePants Movie",
    "vhsYear": 2005,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0018",
    "title": "Indiana Jones Raiders Of The Lost Ark",
    "vhsYear": 1999,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0019",
    "title": "Small Soldiers",
    "vhsYear": 1998,
    "studio": "Dreamworks",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0020",
    "title": "Men In Black",
    "vhsYear": 2000,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0021",
    "title": "Spider-Man",
    "vhsYear": 2002,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0022",
    "title": "Mission Impossible",
    "vhsYear": 1996,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0023",
    "title": "Close Encounters Of The Third Kind",
    "vhsYear": 1998,
    "studio": "Collectors Edition",
    "edition": "Collector's Edition / Metallic Sleeve",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "metallic sleeve; Columbia pictures",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0024",
    "title": "Top Gun",
    "vhsYear": 1996,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0025",
    "title": "Vegas Vacation",
    "vhsYear": 1997,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0026",
    "title": "Ferris Bueller's Day Off",
    "vhsYear": 1986,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0027",
    "title": "Last Action Hero",
    "vhsYear": 1993,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0028",
    "title": "Honey I Shrunk The Kids",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "with special attraction \"tummy trouble\" Roger rabbit short",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0029",
    "title": "Honey I Blew Up The Kid",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0030",
    "title": "Thunderbirds",
    "vhsYear": 2004,
    "studio": "Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0031",
    "title": "Jurassic Park Collectors Edition",
    "vhsYear": 2000,
    "studio": "Universal",
    "edition": "Collector's Edition / 2-Tape Set",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "2 tapes, includes bonus features tape; wide sleeve holding 2 tapes",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0032",
    "title": "Rookie Of The Year",
    "vhsYear": 2000,
    "studio": "20Th Century Fox",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0033",
    "title": "Wayne's World",
    "vhsYear": 1992,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0034",
    "title": "Hot Wheels World Race",
    "vhsYear": 2003,
    "studio": "Family Home Entertainment",
    "edition": "Lenticular",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "lenticular cover",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0035",
    "title": "Phantom Menace",
    "vhsYear": 2000,
    "studio": "20Th Century Fox",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0036",
    "title": "Liar Liar",
    "vhsYear": 1997,
    "studio": "Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0037",
    "title": "So I Married An Axe Murderer",
    "vhsYear": 1997,
    "studio": "Tri Star",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0038",
    "title": "Spider-Man 2",
    "vhsYear": 2004,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0039",
    "title": "Short Circuit",
    "vhsYear": 1992,
    "studio": "Fox Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "20th century Fox selections",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0040",
    "title": "Jackass The Movie",
    "vhsYear": 2002,
    "studio": "Paramount",
    "edition": "Special Edition",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "special edition",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0041",
    "title": "School Of Rock",
    "vhsYear": 2004,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0042",
    "title": "Spaceballs The Video",
    "vhsYear": 1988,
    "studio": "Mgm Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0043",
    "title": "Anchorman",
    "vhsYear": 2004,
    "studio": "Dreamworks",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0044",
    "title": "Uncle Buck",
    "vhsYear": 1989,
    "studio": "MCA Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0045",
    "title": "Bruce Almighty",
    "vhsYear": 2003,
    "studio": "Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0046",
    "title": "Fly Away Home",
    "vhsYear": 1996,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0047",
    "title": "The Greatest Showman",
    "vhsYear": 2017,
    "studio": "20Th Century Fox",
    "edition": "Custom Tape",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "custom tape",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0048",
    "title": "Billy Madison",
    "vhsYear": 1995,
    "studio": "MCA Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0049",
    "title": "Beverly Hills Ninja",
    "vhsYear": 1996,
    "studio": "Tri Star Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0050",
    "title": "Jurassic Park The Lost World Collectors Edition",
    "vhsYear": 2000,
    "studio": "Universal",
    "edition": "Collector's Edition / 2-Tape Set",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "2 tapes, 1 tape with bonus features; double sleeve 2 tapes",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0051",
    "title": "Jurassic Park 3",
    "vhsYear": 2001,
    "studio": "Universal",
    "edition": "Metallic Sleeve",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "metallic sleeve",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0052",
    "title": "Mars Attacks",
    "vhsYear": 2000,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "warner brothers hits",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0053",
    "title": "Mrs Doubtfire",
    "vhsYear": 1994,
    "studio": "Fox Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0054",
    "title": "Pirates Of The Caribbean",
    "vhsYear": 2003,
    "studio": "Curse Of The Black Pearl",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "Walt Disney pictures",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0055",
    "title": "Who Framed Roger Rabbit",
    "vhsYear": "",
    "studio": "Touchstone Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0056",
    "title": "Muppets from Space",
    "vhsYear": 1999,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0057",
    "title": "Hook",
    "vhsYear": 1992,
    "studio": "Tri Star",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0058",
    "title": "Dumb and Dumber",
    "vhsYear": 1995,
    "studio": "Alliance Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0059",
    "title": "The Adventures Of Rocky And Bullwinkle",
    "vhsYear": 2000,
    "studio": "Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0060",
    "title": "Shrek Special Edition",
    "vhsYear": 2001,
    "studio": "Dreamworks",
    "edition": "Special Edition",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "extended ending; regular size sleeve",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0061",
    "title": "Shrek 2",
    "vhsYear": 2004,
    "studio": "Dreamworks",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "far far away idol included",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0062",
    "title": "Zoolander",
    "vhsYear": 2002,
    "studio": "Paramount",
    "edition": "Special Edition",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "special edition",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0063",
    "title": "Clueless",
    "vhsYear": 1995,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0064",
    "title": "Dogtown And Z-Boys",
    "vhsYear": 2002,
    "studio": "Sony Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0065",
    "title": "Happy Gilmore",
    "vhsYear": 2000,
    "studio": "Universal",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "universal comedy greats",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0066",
    "title": "Indiana Jones Temple Of Doom",
    "vhsYear": 1999,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0067",
    "title": "Indiana Jones Last Crusade",
    "vhsYear": 1999,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0068",
    "title": "Black Sheep",
    "vhsYear": 1996,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0069",
    "title": "Shark Tale",
    "vhsYear": 2005,
    "studio": "Dreamworks",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0070",
    "title": "Austin Powers Gold Member",
    "vhsYear": 2002,
    "studio": "Alliance Atlantis",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0071",
    "title": "Ace Ventura Pet Detective",
    "vhsYear": 1994,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0072",
    "title": "Ace Ventura When Nature Calls",
    "vhsYear": 1995,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0073",
    "title": "The Cable Guy",
    "vhsYear": 1996,
    "studio": "Columbia Pictures",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0074",
    "title": "Dodgeball",
    "vhsYear": 2004,
    "studio": "20Th Century",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0075",
    "title": "Bill & Ted's Excellent Adventure",
    "vhsYear": 1989,
    "studio": "Nelson Entertainment",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0076",
    "title": "Beavis And Butthead Do America",
    "vhsYear": 1997,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0077",
    "title": "Teenage Mutant Ninja Turtles III",
    "vhsYear": 1993,
    "studio": "Alliance Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0078",
    "title": "Teenage Mutant Ninja Turtles Secret Of The Ooze",
    "vhsYear": 1991,
    "studio": "Alliance Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0079",
    "title": "Teenage Mutant Ninja Turtles",
    "vhsYear": 1990,
    "studio": "Alliance Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0080",
    "title": "Alien Resurrection",
    "vhsYear": 1999,
    "studio": "20Th Century Fox",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0081",
    "title": "The Sandlot",
    "vhsYear": 2000,
    "studio": "20Th Century Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "20th century family feature",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0082",
    "title": "Karate Kid",
    "vhsYear": 1994,
    "studio": "Columbia Tri Star Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Action / Adventure",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0083",
    "title": "Austin Powers The Spy Who Shagged Me",
    "vhsYear": 1999,
    "studio": "Alliance Atlantis",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0084",
    "title": "The Neverending Story",
    "vhsYear": 1991,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0085",
    "title": "Bean The Ultimate Disaster Movie",
    "vhsYear": 1997,
    "studio": "Polygram Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0086",
    "title": "Star Wars Attack Of The Clones",
    "vhsYear": 2002,
    "studio": "20Th Century Fox",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0087",
    "title": "Star Wars Episode 4 A New Hope",
    "vhsYear": 1995,
    "studio": "20Th Century Fox",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0088",
    "title": "Star Wars Episode 5 Empire Strikes Back",
    "vhsYear": 1990,
    "studio": "CBS Fox",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0089",
    "title": "Star Wars Episode 6 Return Of The Jedi",
    "vhsYear": 1995,
    "studio": "Unknown",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0090",
    "title": "From Star Wars To Jedi The Making Of A Saga",
    "vhsYear": 1995,
    "studio": "20Th Century",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0091",
    "title": "Harry Potter The Philosophers Stone",
    "vhsYear": 2001,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0092",
    "title": "Harry Potter The Chamber Of Secrets",
    "vhsYear": 2002,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0093",
    "title": "Harry Potter The Prisoner Of Azkaban",
    "vhsYear": 2004,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0094",
    "title": "Lord Of The Rings Fellowship Of The Rings",
    "vhsYear": 2001,
    "studio": "Alliance Atlantis",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0095",
    "title": "Thomas And The Magic Railroad",
    "vhsYear": 2000,
    "studio": "Columbia Tri Star",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0096",
    "title": "Tommy Boy",
    "vhsYear": 1995,
    "studio": "Paramount",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0097",
    "title": "The Waterboy",
    "vhsYear": 1999,
    "studio": "Touchstone Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Comedy",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0098",
    "title": "Goof Troop",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "the race is on, 2 episodes",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0099",
    "title": "WWF",
    "vhsYear": 1998,
    "studio": "D-Generation X",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "WF home video",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0100",
    "title": "Flight Of The Navigator",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0101",
    "title": "Freewheel Burning",
    "vhsYear": "",
    "studio": "Freeride",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "mountain bike VHS",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0102",
    "title": "Miracle In Lane 2",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Screener",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "screener copy",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0103",
    "title": "Nintendo Donkey Kong Country",
    "vhsYear": 1994,
    "studio": "Nintendo",
    "edition": "Nintendo Power",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "Nintendo power release",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0104",
    "title": "Nintendo 64 Change The System",
    "vhsYear": 1996,
    "studio": "Nintendo",
    "edition": "Nintendo Power",
    "packaging": "Sleeve",
    "genre": "Other",
    "condition": "",
    "notes": "Nintendo power release",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0105",
    "title": "Jurassic Park 3",
    "vhsYear": 2001,
    "studio": "Universal",
    "edition": "Screener",
    "packaging": "Sleeve",
    "genre": "Sci‑Fi / Fantasy",
    "condition": "",
    "notes": "screener tape",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0106",
    "title": "Walt Disney World Resort In Florida",
    "vhsYear": "",
    "studio": "Walt Disney Parks",
    "edition": "Disney Parks",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "vacation planning VHS; no inserts",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0107",
    "title": "Walt Disney World 25Th Anniversary",
    "vhsYear": 1996,
    "studio": "Walt Disney Parks",
    "edition": "Disney Parks",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "vacation planning; with inserts included",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0108",
    "title": "Disney Song Along Songs",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Sleeve",
    "genre": "Family",
    "condition": "",
    "notes": "zip a dee doo dah",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0109",
    "title": "Toy Story",
    "vhsYear": 1995,
    "studio": "Walt Disney/Pixar",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0110",
    "title": "Toy Story 2",
    "vhsYear": 2000,
    "studio": "Walt Disney/Pixar",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0111",
    "title": "Monsters Inc",
    "vhsYear": 2000,
    "studio": "Walt Disney/Pixar",
    "edition": "Blue Tape",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "blue tape",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0112",
    "title": "Cool Runnings",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0113",
    "title": "Treasure Planet",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0114",
    "title": "Pokémon 2000",
    "vhsYear": 2000,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0115",
    "title": "Pokémon The First Movie",
    "vhsYear": 1999,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0116",
    "title": "Pokémon 3 The Movie",
    "vhsYear": 2001,
    "studio": "Warner Brothers",
    "edition": "Lenticular",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "includes promo card, and lenticular token",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0117",
    "title": "Donkey Kong Country Legend Of The Crystal Coconut",
    "vhsYear": 1996,
    "studio": "Nelvana",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "yellow",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0118",
    "title": "Pee-wee's Big Adventure",
    "vhsYear": 2000,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0119",
    "title": "The Muppet Movie",
    "vhsYear": 1993,
    "studio": "Jim Henson Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "green",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0120",
    "title": "Ducktales The Movie Treasure Of The Lost Lamp",
    "vhsYear": 1991,
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0121",
    "title": "A Goofy Movie",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0122",
    "title": "Space Jam",
    "vhsYear": 1996,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0123",
    "title": "Dark Crystal",
    "vhsYear": 1994,
    "studio": "Jim Henson",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Other",
    "condition": "",
    "notes": "green",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0124",
    "title": "Iron Giant",
    "vhsYear": 1999,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0125",
    "title": "The Goonies",
    "vhsYear": 1994,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0126",
    "title": "Haunted Mansion",
    "vhsYear": "",
    "studio": "Walt Disney Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0127",
    "title": "Mvp 2",
    "vhsYear": 2001,
    "studio": "Warner Brothers",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Other",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0128",
    "title": "Heavyweights",
    "vhsYear": "",
    "studio": "Walt Disney Home Video",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0129",
    "title": "Goosebumps",
    "vhsYear": 1996,
    "studio": "20Th Century Fox",
    "edition": "Standard",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "a night in terror tower",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0130",
    "title": "Disney Land The Happiest Place On Earth",
    "vhsYear": "",
    "studio": "Walt Disney Parks",
    "edition": "Disney Parks",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0131",
    "title": "Disneyland The Lion King Celebration",
    "vhsYear": "",
    "studio": "Walt Disney Parks",
    "edition": "Disney Parks",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  },
  {
    "id": "VHS-0132",
    "title": "Walt Disney World 100 Years Of Magic",
    "vhsYear": 2001,
    "studio": "Walt Disney Parks",
    "edition": "Disney Parks",
    "packaging": "Clamshell",
    "genre": "Family",
    "condition": "",
    "notes": "",
    "cover": "",
    "favorite": false,
    "watched": false,
    "rating": "",
    "photos": [],
    "dateAcquired": "",
    "purchaseLocation": "",
    "purchasePrice": "",
    "tapeCondition": "",
    "sleeveCondition": "",
    "inserts": "",
    "tags": "",
    "timelineNote": ""
  }
];
